#pragma once

enum class CommandType {
    DISPLAY_CURRENT_STOCK,
    DISPLAY_FIRST_SCREEN,
    DISPLAY_PREPAY_LOCATION,
    DISPLAY_ENTER_CARD_NUM,
    DISPLAY_PAYMENT_RESULT_SCREEN,
    DISPLAY_BEVERAGE,
    DISPLAY_CERT_CODE_ENTER,
    DISPLAY_CERT_CODE_FAILED,
    UNKNOWN};